# Generated by Django 4.2.1 on 2024-03-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.BooleanField(default=False)),
                ('non_worker', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='', max_length=20)),
                ('second', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=30)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpageapp.foreg')),
            ],
        ),
    ]
