# Generated by Django 4.2.1 on 2024-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='second',
            field=models.BooleanField(choices=[(1, 'True'), (0, 'False')], default=1),
        ),
    ]
