# Generated by Django 4.2.1 on 2024-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpageapp', '0002_alter_model_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('created_date', models.CharField(max_length=255)),
            ],
        ),
    ]
