# Generated by Django 4.2.1 on 2024-02-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpageapp', '0004_alter_model_worker_or_not'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='worker_or_not',
        ),
    ]
